import '../l10n/string_extensions.dart';

/// Base class for all all client-side errors that can be generated by the app
sealed class AppException implements Exception {
  final String code;
  final String message;

  const AppException(
    this.code,
    this.message,
  );

  @override
  String toString() => message;
}

/// Auth
class WrongCredentials extends AppException {
  WrongCredentials() : super('wrong-credentials', 'Wrong credentials'.hardcoded);
}

class UserNotFoundException extends AppException {
  UserNotFoundException() : super('user-not-found', 'User not found'.hardcoded);
}

class WrongPasswordException extends AppException {
  WrongPasswordException() : super('wrong-password', 'Wrong password'.hardcoded);
}
